services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    read_only: true
    tmpfs:
      - /tmp
    command:
      - "--log.level=${LOG_LEVEL}"
      - "--entrypoints.web.address=:${HTTP_PORT:-80}"
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${TRAEFIK_CONFIGS_PATH}/traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "${TRAEFIK_CONFIGS_PATH}/config:/config:ro"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_BIND_SERVICE

networks:
  traefik:
    external: true
