services:
  traefik:
    restart: unless-stopped
    command:
      - "--log.level=${LOG_LEVEL}"
      # Traefik will listen to incoming request on the port HTTPS_PORT (https)
      - "--entrypoints.websecure.address=:${HTTPS_PORT:-443}"
      # Redirect from http to https
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Enable a http challenge named "cert_resolver"
      - "--certificatesresolvers.cert_resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.cert_resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.cert_resolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.cert_resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - /etc/letsencrypt:/letsencrypt:rw
