version: "3.8"

services:
  traefik:
    image: traefik:v2.4
    # user: ${USER} # traefik requires access to /var/run/docker.sock which is owned by root on non-root docker installations
    read_only: true
    tmpfs:
      - /tmp
    command:
      - "--log.level=ERROR"
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.rule=Host(`${BASE_DOMAIN}.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"

networks:
  traefik:
    external: true
