version: "3.8"

services:
  traefik:
    image: traefik:v2.4
    read_only: true
    tmpfs:
      - /tmp
    command:
      - "--log.level=${LOG_LEVEL}"
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
