version: "3.8"

services:
  traefik:
    command:
      - "--log.level=ERROR"
      - "--api.insecure=true"
      # Enabling docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--tracing.serviceName=traefik"
      - "--tracing.zipkin.httpEndpoint=http://zipkin.${BASE_DOMAIN}.localhost/api/v2/spans"

  zipkin-slim:
    image: ghcr.io/openzipkin/zipkin-slim
    read_only: true
    tmpfs:
      - /tmp
    expose:
      - "9411"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${PROJECT_NAME}_zipkin.loadbalancer.server.port=9411"
      - "traefik.http.routers.${PROJECT_NAME}_zipkin.rule=Host(`zipkin.${BASE_DOMAIN}.localhost`)"
      - "traefik.http.routers.${PROJECT_NAME}_zipkin.entrypoints=web"
