version: "3.8"

services:
  traefik:
    restart: always
    command:
      - "--log.level=${LOG_LEVEL}"
      # Enabling docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Traefik will listen to incoming request on the port 443 (https)
      - "--entrypoints.websecure.address=:443"
      # Redirect from http to https
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Enable a http challenge named "cert_resolver"
      - "--certificatesresolvers.cert_resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.cert_resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.cert_resolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.cert_resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      # Create a letsencrypt dir within the folder where the docker-compose file is
      - /etc/letsencrypt:/letsencrypt:rw
